---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-configmap
  namespace: codeserver
data:
  TZ: Asia/Singapore
  DEFAULT_WORkSPACE: /config/workspace
---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserver
type: Opaque
data:
  PASSWORD: Y2hhbmdlaXQ=
  SUDO_PASSWORD: Y2hhbmdlaXQ=
