---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
  labels:
    app: codeserver
    name: codeserver-pvc
spec:
  resources:
    requests:
      storage: 256Mi
      cpu: 200m
    limits:
      storage: 256Mi
      cpu: 200m
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
