apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp
      tier: web
      name: bggapp-pod
  template:
    metadata:
      name: bggapp-pod
      labels:
        app: bggapp
        tier: web
        name: bggapp-pod
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: bgg-configmap
            - secretRef:
                name: bgg-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
    tier: web
    name: bggapp-svc
spec:
  type: NodePort
  selector:
    app: bggapp
    tier: web
    name: bggapp-pod
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
