---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bggdb-vpc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-vpc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
